# Combine the messages into a dictionary
samples = {
    'support': [
        "Hi, I have an issue with my order. It hasn't arrived, and the delivery date has passed.",
        "My product arrived damaged. How can I request a replacement or refund?",
        "What is the return process? I'm not satisfied with my purchase.",
        "What are the available shipping options and their costs?",
        "I'm having trouble logging into my account. Can you help me reset my password?",
        "Can I track my order? I'm eager to know its status.",
        "The item I received is different from what I ordered. What should I do?",
        "I need assistance with a billing issue. Who can help me with that?",
        "Is there a customer support hotline I can call for immediate help?",
        "Do you have a live chat option for real-time support?",
        "I received a defective product. How can I arrange a replacement?",
        "My package is marked as delivered, but I haven't received it. What should I do?",
        "Can I change the delivery address for my order that's already been placed?",
        "How can I check the warranty status of my recently purchased product?",
        "What is your policy on returns for international orders?",
        "I accidentally placed an order. Can I cancel it before it ships?",
        "The website is not loading properly. Is there an issue with your servers?",
        "Do you have a mobile app, and how can I download it?",
        "I'd like to provide feedback on my customer service experience. How can I do that?",
        "My account shows a double charge for the same order. Can you help resolve this issue?",
        "What is the average response time for customer support inquiries?",
        "Can I escalate my issue to a supervisor if it's not resolved satisfactorily?",
        "Are there any known issues with your website or services currently?",
        "How can I add multiple items to my cart and check out together?",
        "Do you have a FAQ section that can address common customer queries?",
    ],
    'sales': [
        "I'm interested in buying a new laptop. What are the best deals you currently have?",
        "When will you release new phone models? I'm thinking of upgrading mine.",
        "Do you offer student discounts on your products?",
        "I want to buy a gift for a friend. What are the most popular options in the store?",
        "Are there any special promotions for Black Friday? I'm planning to do some shopping.",
        "Can you recommend a budget-friendly smartphone with good features?",
        "What financing options are available for purchasing high-end electronics?",
        "I'm looking for a gaming laptop. Any recommendations on the latest models?",
        "Are there bundle deals available for purchasing multiple products together?",
        "Do you have a loyalty program for repeat customers?",
        "I'm a photographer looking for a high-quality camera. What models do you suggest?",
        "Can you provide information on the trade-in program for old electronic devices?",
        "What are the key features of the latest smartwatches in your collection?",
        "I'm interested in setting up a home office. Can you recommend essential tech products?",
        "Do you offer customization options for laptops, such as upgrading RAM or storage?",
        "I need a new tablet for digital art. Any recommendations for models with a stylus?",
        "Are there any upcoming sales or promotions I should wait for before making a purchase?",
        "I'm interested in virtual reality products. What options do you have available?",
        "Can you provide details on the warranty coverage for your electronics?",
        "I'm a small business owner looking to purchase computers in bulk. Are there discounts available?",
        "What is your return policy if I'm not satisfied with my purchase?",
        "Are there any exclusive online-only deals that I should be aware of?",
        "Do you have a showroom where I can try out products before making a purchase?",
        "Can I pre-order upcoming product releases to secure them on the launch day?",
        "How can I sign up for newsletters to receive updates on new products and promotions?",
    ],
    'joke': [
        "Hello, I'm a robot, and I want to take over the world!",
        "Tell me a joke, please.",
        "What's your favorite food, chatbot?",
        "Are you more of a Star Wars or Star Trek fan?",
        "What is your dream, chatbot?",
        "Why did the computer go to therapy? It had too many bytes of emotional baggage.",
        "What's a chatbot's favorite type of humor? Artificial wit!",
        "How do robots pay for things? With cache, of course!",
        "Why did the robot go on a diet? It had too many bytes!",
        "What's a chatbot's favorite movie? 'The Social Network'—it's all about bytes and connections!",
        "Why did the robot bring a ladder to the bar? It heard the drinks were on the house!",
        "How does a chatbot make a decision? It uses algorithm-ination!",
        "Why did the chatbot go to school? To improve its byte-size!",
        "What's a robot's favorite dance? The algorithm!",
        "Why did the chatbot break up with its computer? It found someone with better bytes.",
        "What do you call a robot that likes to take naps? A recharger!",
        "Why did the chatbot become a musician? It had great algorithms for creating beats!",
        "What's a robot's favorite snack? Microchips!",
        "How does a chatbot express love? In binary!",
        "Why did the chatbot cross the road? To optimize its path-finding algorithm!",
        "What's a chatbot's favorite type of music? Electric tunes!",
        "Why did the robot go to a comedy club? It wanted to upgrade its sense of humor!",
        "What's a chatbot's favorite social media platform? Circuit-gram!",
        "Why did the chatbot apply for a job at the bakery? It wanted to work on its bread-first search algorithm!",
        "What do you call a robot that likes to tell stories? A narrative processor!"
    ]
}

